// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiRM30fm7fEkzB7e7IIEjVfxLSKWh1Bz0',
    appId: '1:931143478831:web:eb32074e7870a5c9c420da',
    messagingSenderId: '931143478831',
    projectId: 'weather-app-9acfc',
    authDomain: 'weather-app-9acfc.firebaseapp.com',
    storageBucket: 'weather-app-9acfc.appspot.com',
    measurementId: 'G-ZYPFWM3QM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfGLsT0JOiCW54J-lVVZGR4vmOBI5GgfY',
    appId: '1:931143478831:android:b2537b0ed149accac420da',
    messagingSenderId: '931143478831',
    projectId: 'weather-app-9acfc',
    storageBucket: 'weather-app-9acfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFxjyeSpCPpHr7DenHfu0-HjXNNoo_TxA',
    appId: '1:931143478831:ios:52bc7f8183952701c420da',
    messagingSenderId: '931143478831',
    projectId: 'weather-app-9acfc',
    storageBucket: 'weather-app-9acfc.appspot.com',
    iosBundleId: 'com.example.weatherForcastTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFxjyeSpCPpHr7DenHfu0-HjXNNoo_TxA',
    appId: '1:931143478831:ios:b34a85b633800fa9c420da',
    messagingSenderId: '931143478831',
    projectId: 'weather-app-9acfc',
    storageBucket: 'weather-app-9acfc.appspot.com',
    iosBundleId: 'com.example.weatherForcastTask.RunnerTests',
  );
}
